UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Beli luk bosut ' WHERE (`id` = '2');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Praziluk Lincoln ' WHERE (`id` = '13');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Praziluk Lancelot' WHERE (`id` = '12');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Srebrenjak Kosma ' WHERE (`id` = '11');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Luk Fiamma' WHERE (`id` = '10');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Crni luk holandski ' WHERE (`id` = '4');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Crni luk holandski 25g' WHERE (`id` = '3');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Crni luk Elenka ' WHERE (`id` = '5');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Rukola Corastar ' WHERE (`id` = '34');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Rukola Celebris ' WHERE (`id` = '33');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Puterica Majska kraljica ' WHERE (`id` = '32');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Puterica Julian  ' WHERE (`id` = '30');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Puterica Daguan ' WHERE (`id` = '29');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Puterica Baglin ' WHERE (`id` = '28');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Puterica Mafalda' WHERE (`id` = '31');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Ferticare I 10g' WHERE (`id` = '66');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Fitofert CINK Org' WHERE (`id` = '73');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Cropcare 11-11-21 ' WHERE (`id` = '65');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Fitofert Bor Max ' WHERE (`id` = '75');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Fitofert Calcium Org' WHERE (`id` = '74');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'SUBSTRAL mineralno tečno' WHERE (`id` = '76');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'FitoFert Kristal 4:10:40' WHERE (`id` = '69');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Ferticare II 24-8-16 ' WHERE (`id` = '67');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Ferticare III 10-5-26 ' WHERE (`id` = '68');
UPDATE `pia_projekat_proba`.`proizvodi` SET `naziv` = 'Fitofert Combivit ' WHERE (`id` = '71');
